packages:
  - packages/*/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

catalog:
  '@babel/eslint-parser': ^7.28.5
  '@babel/preset-env': ^7.28.5
  '@babel/preset-react': ^7.28.5
  '@eslint/js': ^9.39.2
  '@kucrut/vite-for-wp': ^0.12.0
  '@prettier/plugin-php': ^0.24.0
  '@stylistic/eslint-plugin': ^5.6.1
  '@types/node': ^25.0.2
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/ui': ^4.0.15
  baseline-browser-mapping: ^2.9.7
  chalk: ^5.6.2
  commander: ^14.0.2
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-react: ^7.37.5
  glob: ^13.0.0
  globals: ^16.5.0
  husky: ^9.1.7
  imagemin: ^9.0.1
  imagemin-svgo: ^11.0.1
  laravel-vite-plugin: ^2.0.1
  postcss-custom-media: ^11.0.6
  postcss-nested: ^7.0.2
  prettier: ^3.7.4
  rollup-plugin-external-globals: ^0.13.0
  sass-embedded: ^1.96.0
  svgo: ^4.0.0
  svgstore: ^3.0.1
  vite: ^7.3.0
  vite-plugin-external: ^6.2.2
  vite-plugin-static-copy: ^3.1.4
  vitest: ^4.0.15
